name: Claude Code

on:
  issue_comment:
    types: [created, edited]
  pull_request_review:
    types: [submitted, edited]
  issues:
    types: [opened, edited]
  pull_request:
    types: [opened, edited, synchronize]
  pull_request_review_comment:
    types: [created, edited]

jobs:
  claude:
    runs-on: ubuntu-latest
    if: contains(github.event.comment.body, '@claude') || contains(github.event.review.body, '@claude') || contains(github.event.issue.body, '@claude') || contains(github.event.pull_request.body, '@claude')
    
    steps:
    - uses: anthropics/claude-code-action@v1
      with:
        anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
        model: claude-3-5-sonnet-20241022
        tools: |
          sudo ./build-fedora.sh
          dnf install
        max_iterations: 3
